modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cannon_economy"
version="${mod_version}"
displayName="Cannon Economy"
description='''
Soil fertility (1-5), admin regenerating ore deposits, HYW netherite→diamond overrides, increased army supply consumption.
'''
authors="Cannon Season I"

[[dependencies.cannon_economy]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cannon_economy]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.cannon_economy]]
modId="hundred_years_war"
mandatory=false
versionRange="[0.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cannon_economy]]
modId="recruits"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cannon_economy]]
modId="village_recruits"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cannon_economy]]
modId="recruitswr"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
